### ISSUE TITLE
Can't apply multiple operations to the same list -- all but the last are ignored

### ISSUE THREAD

**Issue by ben-g-** [pacha/cels#12]
Generally, having multiple list operations in the same patch works fine. For example, this has the expected behavior:
```
# input
list1:
- a
- b
list2:
- c

# patch
list1 {delete_value}: b
list2 {insert}: d

# output
list1:
- a
list2:
- c
- d
```

However, applying multiple operations to the _same_ list doesn't work. Apparently only the last operation is applied. For example:
```
# input
list:
- a
- b
- c

# patch
list {delete_value}: b
list {insert}: d

# expected output
list:
- a
- c
- d

# actual output
list:
- a
- b
- c
- d
```

(Or am I doing it wrong?)

**Comment by pacha** [comment]
Hi @ben-g-!
I think that what you're looking for is the `change` operation which allows you to perform multiple changes to a single key:
https://github.com/pacha/cels?tab=readme-ov-file#multiple-changes-for-a-same-key

The patch file specifies the changes to be made to _each_ key. That means that if you add the same key multiple times only the last entry will be applied as you noted in your comment. The `change` operation, however, allows you to combine multiple changes together though:
```yaml
# input
list:
- a
- b
- c

# patch
list {change}:
- operation: delete_value
  value: b
- operation: insert
  value: d

# output
list:
- a
- c
- d
```
