### ISSUE TITLE
in-place {render}

### ISSUE THREAD

**Issue by HarlanH** [pacha/cels#8]
I'm playing with cels and generally like the simplicity of what I see, but I'm trying to figure out if it's possible to do an in-place "render" operation.

The use case is a file that looks like:

```
section:
  - asdf
  - replace $ME with something else
 ```

And I'd like to write a patch that looks something like:

```
section {render@1}: "{{ this | replace('$ME', 'qwerty') }}"
```

It seems like the render functionality is assuming that you're processing a variable, but it also seems like variables are expected to be in the patch, not the original document. Is there a way to do this, either directly, or by somehow pulling a value from the original document into a variable?

**Comment by pacha** [comment]
Hi @HarlanH!
That is a very interesting idea. I went ahead and implemented a variation in version `0.3.0`. Instead of referencing the current value of the original document, now you can just use any value from it using the `_get()` template function:
```yaml
# input
section:
  - asdf
  - replace $ME with something else

# patch
section {render@1}: "{{ _get('.section[1]') | replace('$ME', 'qwerty') }}"

# output
section:
  - asdf
  - replace qwerty with something else
```
The `_get()` function takes the path to the value of the original document that you want to use as a dot-notation string (same as the one used for the `link` operation).
https://github.com/pacha/cels?tab=readme-ov-file#repeating-content-from-the-input-document
Hope this covers your use case!
